### ISSUE TITLE
ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.

### ISSUE THREAD

**Issue by me2d09** [gb119/Stoner-PythonCode#17]
When loading standard PPMS datafile [test.txt](https://github.com/gb119/Stoner-PythonCode/files/2133403/test.txt) it is not possible to show its records. Try this code:
```
from Stoner import Data
data=Data('test.txt')
data.records
```
Problem is when calling self.data.view(dtype=dtype) in Core.py (https://github.com/gb119/Stoner-PythonCode/blob/master/Stoner/Core.py#L913)

With data from VSM PPMS option it is working fine so I have no idea why this error is produced just for this datafile.

**Comment by gb119** [comment]
Ok, so the underlying reason seems to be a mismatch between the number of column headers and the number of columns of data. The new dtype for the record array is being created from the column headers it seems and then the error happens because there aren't the requisite number of data elements to interpret it as the new record. The question is why....?

**Comment by gb119** [comment]
Ok, so there seems to be a problem with the number of commas in the rows of data does not match the number of column header values (-1). I think the real bug is with the QD software (it's an insane format to put all possible variables as a column anyway!) but we ought to detect and work around it. Next commit will fix this.
