### ISSUE TITLE
Problem inheriting from Data

### ISSUE THREAD

**Issue by rowan-uk** [gb119/Stoner-PythonCode#8]
max recursion depth reached in DataFile getattr when accessing unknown attribute in inherited class. (problem with DataFile._mro)

from Stoner import Data
class Test(Data):
    def __init__(self):
        super(Test, self).__init__()
        a=self.test1   
t=Test()
print(t)

**Comment by gb119** [comment]
I think this is fixed in the current 0.7b2 release where I've refactored the mixin inheritance to avoid this issue.

**Comment by dvincentwest** [comment]
I have the up to date release (I think)

I am having a similar issue when reading RAS files.  If I just read the file with the Stoner.FileFormats.Rigaku class, everything seems okay with normal test.  If I try to create a class with the PlotMixin and then call plot, I get a recursion error.  I don't know if I am doing something wrong or not

This works

```
spc = Stoner.FileFormats.RigakuFile(fname)
columns = spc.columns()
x = next(columns)
y = next(columns)
plot(x, y)
```

This does not work:

```
class myras(Stoner.FileFormats.RigakuFile, Stoner.plot.PlotMixin):
    pass
spc = myras(fname)
spc.plot()
```

the call to spc.plot gives the following traceback where the last segment goes on to infinity:

```
C:\Miniconda3\lib\site-packages\Stoner\plot\core.py in plot(self, *args, **kargs)
    749         if 2 <= axes <= 6:
    750             plotter = plotters[axes]
--> 751             ret = plotter(*args, **kargs)
    752             plt.show()
    753         else:

C:\Miniconda3\lib\site-packages\Stoner\plot\core.py in plot_xy(self, xcol, ycol, fmt, xerr, yerr, multiple, **kargs)
    989                 self.__figure, ax = self._fix_fig(self.__figure)
    990         else:
--> 991             self.__figure, ax = self._fix_fig(nonkargs["figure"])
    992         for ix in range(len(c.ycol)):
    993             if multiple != "common":

C:\Miniconda3\lib\site-packages\Stoner\plot\core.py in _fix_fig(self, figure, **kargs)
    344             ax = self.__figure.gca(**kargs)
    345         else:
--> 346             figure, ax = self.template.new_figure(None, **kargs)
    347         return figure, ax
    348 

C:\Miniconda3\lib\site-packages\Stoner\plot\core.py in template(self)
    145     @property
    146     def template(self):
--> 147         if not hasattr(self,"_template"):
    148             self.template=DefaultPlotStyle
    149         return self._template

C:\Miniconda3\lib\site-packages\Stoner\Core.py in __getattr__(self, name)
   2203             if c not in (DataFile,metadataObject):
   2204                 try:
-> 2205                     ret = c.__getattr__(self,name)
   2206                     return ret
   2207                 except RecursionError:
```

**Comment by gb119** [comment]
The order in which you put the parent classes when doing multiple inheritance matters when you have mxin classes. You want to have the base class (in this case the RigakuFile) as the last class in the inheritance list (this isn't specific to this library, it's just to do with how Python's method resolution order works.)

In your version myras the method resolution order is:
(__main__.myras,
 Stoner.FileFormats.RigakuFile,
 Stoner.Core.DataFile,
 Stoner.Core.metadataObject,
 _abcoll.MutableMapping,
 _abcoll.Mapping,
 _abcoll.Sized,
 _abcoll.Iterable,
 _abcoll.Container,
 Stoner.plot.core.PlotMixin,
 object)

Swapping it around so that PlotMixin is first in the list give:

(__main__.myras,
 Stoner.plot.core.PlotMixin,
 Stoner.FileFormats.RigakuFile,
 Stoner.Core.DataFile,
 Stoner.Core.metadataObject,
 _abcoll.MutableMapping,
 _abcoll.Mapping,
 _abcoll.Sized,
 _abcoll.Iterable,
 _abcoll.Container,
 object)

and so all of the PlotMixin attributes get picked up before it starts trying to see if it can do 'magic' matches against column headers.

**Comment by gb119** [comment]
In fairness, the definition of PlotFile and AnalysFile in master are broken in this way - a few revisions ago I had a crazy hacked-up mixin scheme that did everything backwards that is mainly, but not entirely put straight into conventional Python style - so thanks for making me look at those bits of code!

**Comment by gb119** [comment]
I think this now works correctly in the current development branch.
